# Generated by Django 5.2.4 on 2026-01-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_user_private_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user'], name='core_log_user_8f5f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['timestamp'], name='core_log_timesta_924942_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['status'], name='core_log_status_f2e4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='core_user_usernam_e8adca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['private_key'], name='core_user_private_9a11c9_idx'),
        ),
    ]
