# Generated by Django 5.2.4 on 2026-01-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aiinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='merkle_root',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
